# This is a basic workflow to help you get started with Actions


on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
        
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd 
